version: 2
project_name: doppler

before:
  hooks:
    - go mod download
    - go mod tidy
    - ./scripts/completions.sh

builds:
  -
    binary: doppler
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - freebsd
      - linux
      - netbsd
      - openbsd
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
    - goos: darwin
      goarch: "386"
    - goos: windows
      goarch: "386"
    - goos: freebsd
      goarch: "386"
    ldflags:
      - -s -w -X github.com/DopplerHQ/cli/pkg/version.ProgramVersion=v{{.Version}}

archives:
-
  name_template: >-
    {{ .ProjectName }}_
    {{- .Version }}_
    {{- if eq .Os "darwin" }}macOS
    {{- else }}{{ .Os }}{{ end }}_
    {{- if eq .Arch "386" }}i386
    {{- else }}{{ .Arch }}{{ end }}
    {{- with .Arm }}v{{ . }}{{ end }}
    {{- with .Mips }}_{{ . }}{{ end }}
    {{- if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}
  format_overrides:
    - goos: windows
      format: zip
  files:
    - README.md
    - LICENSE
    - completions/*

release:
  github:
    owner: DopplerHQ
    name: cli

  footer: |
    ## Docker images

    - `docker pull dopplerhq/cli:{{ .Version }}`
    - `docker pull dopplerhq/cli:{{ .Major }}.{{ .Minor }}`
    - `docker pull dopplerhq/cli:{{ .Major }}`

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

source:
  enabled: true
  name_template: '{{ .ProjectName }}_{{ .Version }}_src'
  format: 'tar.gz'

signs:
  -
    artifacts: all
    args:
      - "-u"
      - "B70BD7FCA460C4A3D0EEB965D3D593D50EE79DEC"
      - "--output"
      - "${signature}"
      - "--batch"
      - "--yes"
      - "--pinentry-mode"
      - "loopback"
      - "--passphrase"
      - "$GPG_PASSPHRASE"
      - "--detach-sign"
      - "${artifact}"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^chore:'
    - Merge pull request
    - Merge branch

dockers:
  - dockerfile: docker/alpine
    goos: linux
    goarch: amd64
    ids:
      - doppler
    image_templates:
      - "dopplerhq/cli:{{ .Version }}"             # Ex: 1.4.2
      - "dopplerhq/cli:{{ .Major }}.{{ .Minor }}"  # Ex: 1.4
      - "dopplerhq/cli:{{ .Major }}"               # Ex: 1
      - "dopplerhq/cli:latest"
      - "gcr.io/dopplerhq/cli:{{ .Version }}"             # Ex: 1.4.2
      - "gcr.io/dopplerhq/cli:{{ .Major }}.{{ .Minor }}"  # Ex: 1.4
      - "gcr.io/dopplerhq/cli:{{ .Major }}"               # Ex: 1
      - "gcr.io/dopplerhq/cli:latest"
    build_flag_templates:
      - "--label=org.label-schema.schema-version=1.0"
      - "--label=org.label-schema.version={{.Version}}"
      - "--label=org.label-schema.name={{.ProjectName}}"
      - "--platform=linux/amd64"

brews:
  - name: doppler
    repository:
      owner: DopplerHQ
      name: homebrew-doppler
    commit_author:
      name: "Doppler Bot"
      email: bot@doppler.com
    directory: Formula
    homepage: "https://doppler.com"
    description: "The official Doppler CLI for managing your secrets"
    install: |-
      bin.install "doppler"
      bash_completion.install "completions/doppler.bash" => "doppler"
      zsh_completion.install "completions/doppler.zsh" => "_doppler"
      fish_completion.install "completions/doppler.fish"
    test: |
      system "#{bin}/doppler --version"

scoops:
  - repository:
      owner: DopplerHQ
      name: scoop-doppler
    commit_author:
      name: "Doppler Bot"
      email: bot@doppler.com
    homepage: "https://doppler.com"
    description: "The official Doppler CLI for managing your secrets"
    license: Apache-2.0

winget:
  - name: doppler
    publisher: Doppler
    short_description: "The official Doppler CLI for managing your secrets"
    license: Apache-2.0
    publisher_url: https://doppler.com
    commit_author:
      name: "Doppler Bot"
      email: bot@doppler.com
    homepage: "https://doppler.com"
    skip_upload: auto
    repository:
      owner: DopplerHQ
      name: winget-pkgs
      branch: "cli-{{.Version}}"
      pull_request:
        enabled: true
        base:
          owner: microsoft
          name: winget-pkgs
          branch: master

nfpms:
  - id: doppler
    file_name_template: >-
      {{ .PackageName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- with .Arm }}v{{ . }}{{ end }}
      {{- with .Mips }}_{{ . }}{{ end }}
      {{- if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}
    homepage: "https://doppler.com"
    maintainer: Doppler Bot <bot@doppler.com>
    description: "The official Doppler CLI for managing your secrets"
    license: Apache-2.0
    bindir: /usr/bin
    formats:
      - deb
      - rpm
      - apk
    contents:
      - src: ./completions/doppler.bash
        dst: /etc/bash_completion.d/doppler
      - src: ./completions/doppler.zsh
        dst: /usr/local/share/zsh/site-functions/_doppler
        packager: deb
      - src: ./completions/doppler.zsh
        dst: /usr/local/share/zsh/site-functions/_doppler
        packager: apk
      - src: ./completions/doppler.zsh
        dst: /usr/share/zsh/site-functions/_doppler
        packager: rpm
      - src: ./completions/doppler.fish
        dst: /usr/share/fish/completions/doppler.fish

blobs:
  -
    provider: gs
    bucket: dopplerhq_cli_releases
    directory: "{{ .Tag }}"
