project_name: doppler

before:
  hooks:
    - go mod tidy

builds:
  -
    binary: doppler
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - freebsd
      - linux
      - netbsd
      - openbsd
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
    - goos: darwin
      goarch: "386"
    - goos: windows
      goarch: "386"
    - goos: freebsd
      goarch: "386"
    ldflags:
      - -s -w -X github.com/DopplerHQ/cli/pkg/version.ProgramVersion=v{{.Version}}

archives:
-
  replacements:
    darwin: macOS
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip

release:
  github:
    owner: DopplerHQ
    name: cli

checksum:
  name_template: 'checksums.txt'

signs:
  -
    artifacts: checksum
    args:
      - "-u"
      - "B70BD7FCA460C4A3D0EEB965D3D593D50EE79DEC"
      - "--output"
      - "${signature}"
      - "--batch"
      - "--yes"
      - "--pinentry-mode"
      - "loopback"
      - "--passphrase"
      - "$GPG_PASSPHRASE"
      - "--detach-sign"
      - "${artifact}"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch

dockers:
  - dockerfile: docker/alpine
    goos: linux
    goarch: amd64
    binaries:
      - doppler
    image_templates:
      - "dopplerhq/cli:{{ .Version }}"             # Ex: 1.4.2
      - "dopplerhq/cli:{{ .Major }}.{{ .Minor }}"  # Ex: 1.4
      - "dopplerhq/cli:{{ .Major }}"               # Ex: 1
      - "gcr.io/dopplerhq/cli:{{ .Version }}"             # Ex: 1.4.2
      - "gcr.io/dopplerhq/cli:{{ .Major }}.{{ .Minor }}"  # Ex: 1.4
      - "gcr.io/dopplerhq/cli:{{ .Major }}"               # Ex: 1
    build_flag_templates:
      - "--label=org.label-schema.schema-version=1.0"
      - "--label=org.label-schema.version={{.Version}}"
      - "--label=org.label-schema.name={{.ProjectName}}"
  - dockerfile: docker/node:alpine
    goos: linux
    goarch: amd64
    binaries:
      - doppler
    image_templates:
      - "dopplerhq/cli:{{ .Version }}-node"
      - "dopplerhq/cli:{{ .Major }}.{{ .Minor }}-node"
      - "dopplerhq/cli:{{ .Major }}-node"
      - "dopplerhq/cli:node"
      - "gcr.io/dopplerhq/cli:{{ .Version }}-node"
      - "gcr.io/dopplerhq/cli:{{ .Major }}.{{ .Minor }}-node"
      - "gcr.io/dopplerhq/cli:{{ .Major }}-node"
      - "gcr.io/dopplerhq/cli:node"
    build_flag_templates:
      - "--label=org.label-schema.schema-version=1.0"
      - "--label=org.label-schema.version={{.Version}}"
      - "--label=org.label-schema.name={{.ProjectName}}"
  - dockerfile: docker/python:alpine
    goos: linux
    goarch: amd64
    binaries:
      - doppler
    image_templates:
      - "dopplerhq/cli:{{ .Version }}-python"
      - "dopplerhq/cli:{{ .Major }}.{{ .Minor }}-python"
      - "dopplerhq/cli:{{ .Major }}-python"
      - "dopplerhq/cli:python"
      - "gcr.io/dopplerhq/cli:{{ .Version }}-python"
      - "gcr.io/dopplerhq/cli:{{ .Major }}.{{ .Minor }}-python"
      - "gcr.io/dopplerhq/cli:{{ .Major }}-python"
      - "gcr.io/dopplerhq/cli:python"
    build_flag_templates:
      - "--label=org.label-schema.schema-version=1.0"
      - "--label=org.label-schema.version={{.Version}}"
      - "--label=org.label-schema.name={{.ProjectName}}"
  - dockerfile: docker/ruby:alpine
    goos: linux
    goarch: amd64
    binaries:
      - doppler
    image_templates:
      - "dopplerhq/cli:{{ .Version }}-ruby"
      - "dopplerhq/cli:{{ .Major }}.{{ .Minor }}-ruby"
      - "dopplerhq/cli:{{ .Major }}-ruby"
      - "dopplerhq/cli:ruby"
      - "gcr.io/dopplerhq/cli:{{ .Version }}-ruby"
      - "gcr.io/dopplerhq/cli:{{ .Major }}.{{ .Minor }}-ruby"
      - "gcr.io/dopplerhq/cli:{{ .Major }}-ruby"
      - "gcr.io/dopplerhq/cli:ruby"
    build_flag_templates:
      - "--label=org.label-schema.schema-version=1.0"
      - "--label=org.label-schema.version={{.Version}}"
      - "--label=org.label-schema.name={{.ProjectName}}"

brews:
  - name: doppler
    github:
      owner: DopplerHQ
      name: homebrew-doppler
    commit_author:
      name: "Doppler Bot"
      email: bot@doppler.com
    folder: Formula
    homepage: "https://doppler.com"
    description: "The official Doppler CLI for managing your secrets and config"
    test: |
      system "#{bin}/doppler --version"

scoop:
  bucket:
    owner: DopplerHQ
    name: scoop-doppler
  commit_author:
    name: "Doppler Bot"
    email: bot@doppler.com
  homepage: "https://doppler.com"
  description: "The official Doppler CLI for managing your secrets and config"
  license: Apache-2.0

nfpms:
  - id: doppler
    replacements:
      386: i386
    homepage: "https://doppler.com"
    maintainer: Doppler Bot <bot@doppler.com>
    description: "The official Doppler CLI for managing your secrets and config"
    license: Apache-2.0
    formats:
      - deb
      - rpm

blobs:
  -
    provider: gs
    bucket: dopplerhq_cli_releases
    folder: "{{ .Tag }}"
