/*
Copyright © 2026 Doppler <support@doppler.com>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package proxy

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"strings"

	agentproxy "github.com/DopplerHQ/agent-proxy"
	"gopkg.in/yaml.v3"
)

// ProxyConfig is the user-editable proxy configuration (doppler-proxy.yaml).
type ProxyConfig struct {
	// ListenAddress is the address the proxy binds. Defaults (via the starter
	// config) to 0.0.0.0:14322 so the `doppler agent run` sandbox can reach it.
	// The --address flag overrides this.
	ListenAddress string `yaml:"listen_address"`

	// Passthrough lists hostnames the proxy blind-tunnels instead of
	// intercepting (no TLS termination, no injection).
	Passthrough []string `yaml:"passthrough"`

	// Bindings declares where each secret may be injected, by secret name. A
	// secret with no entry falls under Unbound.
	Bindings map[string][]agentproxy.Rule `yaml:"bindings"`

	// Unbound is the policy for a secret with no bindings entry: "deny" (the
	// default) refuses it everywhere, "trust-first-use" pins it to the first
	// host the agent sends it to.
	Unbound string `yaml:"unbound"`

	// Methods declares a non-static credential method per secret name. A secret with
	// no entry uses the static method: its masked value is swapped in a header.
	Methods map[string]CredentialMethod `yaml:"methods"`
}

// CredentialMethod is how a secret is brokered onto a request (doppler-proxy.yaml).
// It maps to agentproxy.MethodConfig.
type CredentialMethod struct {
	// Kind: "static" (default), "oauth2_client_credentials", or "aws_sigv4".
	Kind string `yaml:"kind"`

	// OAuth2 client-credentials (kind: oauth2_client_credentials). The secret's value
	// is the client secret; the proxy exchanges it for a bearer and injects that.
	TokenURL string   `yaml:"token_url"`
	ClientID string   `yaml:"client_id"`
	Scopes   []string `yaml:"scopes"`

	// AWS SigV4 (kind: aws_sigv4). The secret is the AWS secret access key; access_key_id
	// names the secret holding the access key id. Region defaults to us-east-1.
	Service     string `yaml:"service"`
	Region      string `yaml:"region"`
	AccessKeyID string `yaml:"access_key_id"`
}

// BindingResolver builds the resolver the proxy authorizes injection with.
func (c *ProxyConfig) BindingResolver() (agentproxy.BindingResolver, error) {
	var policy agentproxy.UnboundPolicy
	switch c.Unbound {
	case "", "deny":
		policy = agentproxy.UnboundDeny
	case "trust-first-use":
		policy = agentproxy.UnboundTOFU
	default:
		return nil, fmt.Errorf("unbound must be deny or trust-first-use, got %q", c.Unbound)
	}
	return agentproxy.NewRuleResolver(c.Bindings, policy), nil
}

// MethodConfigs maps the user's credential-method declarations to the agent-proxy
// method registry. Returns nil when none are declared (every secret is static).
func (c *ProxyConfig) MethodConfigs() map[string]agentproxy.MethodConfig {
	if len(c.Methods) == 0 {
		return nil
	}
	out := make(map[string]agentproxy.MethodConfig, len(c.Methods))
	for name, m := range c.Methods {
		out[name] = agentproxy.MethodConfig{
			Kind:        m.Kind,
			TokenURL:    m.TokenURL,
			ClientID:    m.ClientID,
			Scopes:      m.Scopes,
			Service:     m.Service,
			Region:      m.Region,
			AccessKeyID: m.AccessKeyID,
		}
	}
	return out
}

// starterConfigHead is the top of the scaffolded config (addressing + passthrough).
// The bindings section between it and starterConfigTail is generated by
// scaffoldBindings so it can be pre-seeded with the operator's own secret names.
const starterConfigHead = `# doppler-proxy.yaml — configuration for the Doppler agent credential proxy.
# Edit this file, then restart the proxy to apply changes.

# Address the proxy listens on. 0.0.0.0 serves both host tools (via 127.0.0.1) and
# the ` + "`doppler agent run`" + ` sandbox container (via the docker bridge). Every client
# must present the per-run proxy token, so a broad bind is not an open proxy. Set
# 127.0.0.1 to bind loopback only (the sandbox container cannot reach that).
# --address overrides this.
listen_address: 0.0.0.0:14322

# Hosts the proxy BLIND-TUNNELS instead of intercepting: no TLS termination, no
# credential injection, and nothing in the audit log. Every entry is a hole we chose,
# so keep this list as short as possible. Removing a host does NOT block it — the host
# is simply intercepted instead (the agent trusts the proxy CA), so it still works and
# is now examined. Only two kinds of host belong here: the agent's own control plane
# that we deliberately don't inspect, and auth endpoints that BREAK under interception
# because they reject an unexpected CA. Matching is exact — there is no wildcard.
passthrough:
  # Claude's model API — the endpoint the agent exists to use. Passed through so the
  # agent's own model traffic is never intercepted.
  - api.anthropic.com
  # Claude Code login/session and OAuth token refresh. Auth endpoints reject the proxy's
  # unexpected CA, so intercepting these breaks sign-in. Kept to Anthropic's first party.
  - console.anthropic.com
  - claude.ai
  - claude.com

`

// starterConfigTail closes out the scaffolded config after the bindings section.
const starterConfigTail = `
# Policy for a secret with no bindings entry. deny refuses it everywhere and
# logs the host it was sent to. trust-first-use pins it to the first host the
# agent uses, which lets the agent decide where the credential goes.
# unbound: deny

# Non-static credential methods, by secret name. A secret omitted here is injected as
# its literal value (static). oauth2_client_credentials exchanges the secret for a
# bearer at token_url and injects that; aws_sigv4 signs the whole request with the AWS
# secret access key (access_key_id names the secret holding the key id; region defaults
# to us-east-1). In every case the agent only ever holds the mask.
# methods:
#   MY_OAUTH_SECRET:
#     kind: oauth2_client_credentials
#     token_url: https://provider.example.com/oauth/token
#     client_id: your-client-id
#     scopes: [read, write]
#   AWS_SECRET_ACCESS_KEY:
#     kind: aws_sigv4
#     service: s3
#     region: us-east-1
#     access_key_id: AWS_ACCESS_KEY_ID
`

// scaffoldBindings renders the commented "bindings" section of the starter config.
// A binding is where security actually happens — it maps a secret NAME to the upstream
// host(s) it may reach — so the template documents the shape and, when the caller can
// enumerate the operator's secret names, pre-seeds one commented stub per secret. That
// way the operator edits real entries instead of transcribing a generic example; with
// no names available it falls back to provider examples. Every stub is commented, so a
// freshly scaffolded config injects nothing until the operator fills in a host.
func scaffoldBindings(secretNames []string) string {
	var b strings.Builder
	b.WriteString(`# Bindings: where each secret may be injected. A binding maps a secret NAME to the
# upstream host(s) it may reach. A secret with no binding is refused everywhere (see
# unbound, below), so this is how you tell the proxy which destination each secret is for.
#   host    — upstream hostname the secret may reach (required)
#   paths   — optional glob list; ** spans path segments. Omit to allow any path.
#   methods — optional [GET, POST, ...]. Omit to allow any method.
# For reference: GITHUB_TOKEN -> api.github.com, STRIPE_SECRET_KEY -> api.stripe.com,
# OPENAI_API_KEY -> api.openai.com.
#
# Uncomment "bindings:" and set the host for each secret you want the agent to use.
# bindings:
`)
	names := secretNames
	if len(names) == 0 {
		// No secret names available — show generic examples instead.
		names = []string{"GITHUB_TOKEN", "STRIPE_KEY"}
	}
	for i, n := range names {
		b.WriteString("#   " + n + ":\n")
		b.WriteString("#     - host: <hostname>\n")
		if i == 0 {
			b.WriteString("#       # paths: [\"/repos/**\"]   # optional: restrict to path globs\n")
			b.WriteString("#       # methods: [GET, POST]     # optional: restrict to HTTP methods\n")
		}
	}
	return b.String()
}

// buildStarterConfig assembles the scaffolded config, pre-seeding the bindings section
// with the given secret names when available.
func buildStarterConfig(secretNames []string) string {
	return starterConfigHead + scaffoldBindings(secretNames) + starterConfigTail
}

// LoadOrScaffold loads the proxy config from path. If the file does not exist (or is
// blank) it writes the starter config and returns it with created=true. secretNames is
// called only when scaffolding, to pre-seed the bindings template with the operator's
// own secret names; it may be nil.
func LoadOrScaffold(path string, secretNames func() []string) (cfg *ProxyConfig, created bool, err error) {
	data, err := os.ReadFile(path)
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return nil, false, err
	}
	// Write the starter config when the file is missing OR empty — so a stray blank
	// file (e.g. from an interrupted write) still gets populated on startup instead
	// of silently loading as an empty config.
	if errors.Is(err, os.ErrNotExist) || len(bytes.TrimSpace(data)) == 0 {
		var names []string
		if secretNames != nil {
			names = secretNames()
		}
		content := buildStarterConfig(names)
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			return nil, false, err
		}
		cfg, err = parseProxyConfig([]byte(content))
		return cfg, true, err
	}
	cfg, err = parseProxyConfig(data)
	return cfg, false, err
}

func parseProxyConfig(data []byte) (*ProxyConfig, error) {
	var cfg ProxyConfig
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil, err
	}
	return &cfg, nil
}

// MergePassthrough returns the config's passthrough hosts plus any extras,
// de-duplicated and order-preserving (config entries first).
func MergePassthrough(cfg *ProxyConfig, extra []string) []string {
	return mergeHostLists(cfg.Passthrough, extra)
}

func mergeHostLists(base, extra []string) []string {
	seen := map[string]bool{}
	var out []string
	for _, s := range append(append([]string{}, base...), extra...) {
		if s == "" || seen[s] {
			continue
		}
		seen[s] = true
		out = append(out, s)
	}
	return out
}
