name: Vulncheck

on:
  pull_request:
  push:
  schedule:
    - cron: "28 1 * * *"

jobs:
  vulncheck:
    name: Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Go Supported Version
        uses: dopplerhq/go-supported-version-check-action@v1
        with:
          go-version: "1.24" # GO_VERSION_DEF
          version-requirement: any-supported
