name: Update Salus GoVersionScanner min_version
on:
  workflow_dispatch:
  schedule:
    - cron: '18 0 * * *'
permissions:
  contents: write
  pull-requests: write

jobs:
  go_version_update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Update min_version
      shell: bash
      run: ./scripts/go-min-version-update.sh
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        commit-message: Update Salus GoVersionScanner min_version
        branch: create-pull-request/salus-go-min-version-update
        delete-branch: true
        title: 'Update Salus GoVersionScanner min_version'
        body: |
          From https://go.dev/doc/devel/release:
          
          > Each major Go release is supported until there are two newer major releases.
          > For example, Go 1.5 was supported until the Go 1.7 release, and Go 1.6 was
          > supported until the Go 1.8 release. We fix critical problems, including critical
          > security problems, in supported releases as needed by issuing minor revisions
          > (for example, Go 1.6.1, Go 1.6.2, and so on).

          We're updating the check to the latest stable release of the previous release
          from current (i.e., if the most recent Go release is 1.26.0, fetch the most recent
          1.25.x version).
          
          Auto-generated by [create-pull-request][1]

          [1]: https://github.com/peter-evans/create-pull-request
