name: Run tests

on: [push]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: '1.16'
    - name: Checkout
      uses: actions/checkout@v1
      with:
        path: ./src/github.com/${{ github.repository }}
    - name: Build
      run: make build
      env:
        GOPATH: ${{ runner.workspace }}
    - name: E2E Tests
      run: make test-e2e
      env:
        DOPPLER_TOKEN: ${{ secrets.E2E_TEST_DOPPLER_TOKEN }}
  unit:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: '1.16'
    - name: Checkout
      uses: actions/checkout@v1
      with:
        path: ./src/github.com/${{ github.repository }}
    - name: Build
      run: make build
      env:
        GOPATH: ${{ runner.workspace }}
    - name: Unit Tests
      run: make test
      env:
        GOPATH: ${{ runner.workspace }}
